ALTER TABLE messages ADD COLUMN pinned_at TEXT;

ALTER TABLE groups ADD COLUMN topic TEXT NOT NULL DEFAULT '';
ALTER TABLE groups ADD COLUMN avatar_file_id BIGINT REFERENCES files(id) ON DELETE SET NULL;
